# HTTP Server
server:
  port: 8888

spring:
  application:
    name: config-server
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://sebramirez@bitbucket.org/sebramirez/config-server-repository.git
